# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-17 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_auto_20190917_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='some notes about the book', max_length=255),
            preserve_default=False,
        ),
    ]
